package com.whb.dbmodule.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.whb.dbmodule.greendao.bean.PasswordBean;

import com.whb.dbmodule.greendao.PasswordBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig passwordBeanDaoConfig;

    private final PasswordBeanDao passwordBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        passwordBeanDaoConfig = daoConfigMap.get(PasswordBeanDao.class).clone();
        passwordBeanDaoConfig.initIdentityScope(type);

        passwordBeanDao = new PasswordBeanDao(passwordBeanDaoConfig, this);

        registerDao(PasswordBean.class, passwordBeanDao);
    }
    
    public void clear() {
        passwordBeanDaoConfig.clearIdentityScope();
    }

    public PasswordBeanDao getPasswordBeanDao() {
        return passwordBeanDao;
    }

}
